server {
    listen 80;
    resolver 127.0.0.11 valid=30s;
    resolver_timeout 5s;

    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_read_timeout 300s;
    proxy_connect_timeout 10s;

    location = /sequenceserver {
        return 301 /sequenceserver/;
    }

    location /sequenceserver/ {
        proxy_pass http://sequenceserver:4567/;
    }

    location /gene_sets {
        allow 127.0.0.1;
        deny all;
        proxy_pass http://expvip:3000;
    }

    location /gene_sets/ {
        limit_except GET {
            allow 127.0.0.1;
            deny all;
        }
        proxy_pass http://expvip:3000;
    }

    location / {
        proxy_pass http://expvip:3000/;
    }

    error_page 404 /404.html;
        location = /404.html {
    }

    error_page 500 502 503 504 /50x.html;
        location = /50x.html {
    }
    
    rewrite ^(/sequenceserver/genes)(.*)$  /genes/$2 permanent;
}